<?php require VIEWS_PATH . 'includes/header.phtml'?>

<main role="main" class="container">

  <div class="jumbotron">
    <h1>Despesas</h1>
    <p class="lead"> Gerenciador de Gastos </p>
  </div>

</main>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Descrição</th>
        <th>Valor</th>
        <th>Criado em</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach($this->expenses as $e):?>
        <tr>
          <td><?=$e['id']?></td>
          <td><?=$e['description']?></td>
          <td>R$ <?=number_format($e['value'], 2,',', '.')?></td>
          <td><?=date('d/m/Y H:i:s', strtotime($e['created_at']))?></td>
          <td>
            <a href="<?=HOME?>/expense/edit/<?=$e['id']?>" class="btn btn-default"> Editar </a>
            <a href="<?=HOME?>/expense/remove/<?=$e['id']?>" class="btn btn-danger"> Excluir </a>
          </td>
        </tr>
      <?php endforeach ?>
    </tbody>
  </table>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'?>
