<?php require VIEWS_PATH . 'includes/header.phtml'?>

<div class="container">

    <h1>Cadastro de despesas</h1>

    <form action="<?=HOME?>/expense/new" method="post">
        <div class="form-group">
            <label for="">Categoria</label>
            <select class="form-control" name="categories_id">
                <?php foreach($this->categories as $c):?>
                    <option value="<?=$c['id']?>"><?=$c['name']?></option>
                <?php endforeach?>
            </select>
        </div>
        <div class="form-group">
            <label for="">Valor</label>
            <input class="form-control" name="value" type="text" required>
        </div>
        <div class="form-group">
            <label for="">Descrição</label>
            <textarea class="form-control" name="description" cols="10" rows="5" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Salvar despesa</button>
    </form>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'?>