<?php require VIEWS_PATH . 'includes/header.phtml'?>

<main role="main" class="container">

  <div class="row">
      <div class="col-md-6">
        <img src="http://via.placeholder.com/350x150?text=<?=$this->product['name']?>" alt="" class="img-responsive">
      </div>
      <div class="col-md-6">
        <img src="" alt="" class="img-responsive">
        <h2><a href="<?=HOME?>/product/<?=$this->product['id']?>"><?=$this->product['name']?></a></h2>
        <p><?=$this->product['description']?></p>
        <p>R$ <?=number_format($this->product['price'], 2, ',', '.')?></p>
      </div>

  </div>


</main>


<?php require VIEWS_PATH . 'includes/footer.phtml'?>
